# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c52bf6c1eecdc51c91659b28373ca30ee703f4fbf20d1b3230da9c63d2c93f496706e12cf597c3f910bd36144dd4870ed4f12def58897e484879a5feef5d7988

test:
  secret_key_base: ad0bc9130b27d4be56fe600a5ac5a049f62d05b6bcd364a306f474ae7f9d480c257b3482607120ce2cf9d8fd857e5d487a80b2f0e10e3c6f13fd8523aae864f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
